### ISSUE TITLE
RuntimeError in Cython when building on macOS

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/snakeoil#59]
macOS (and Windows) default to the 'spawn' multiprocessing method which breaks a lot of consumers like Cython.

There's a bug reported to Cython [here](https://github.com/cython/cython/issues/3262). For now, we can either force nthreads=1 when spawn is the multiprocessing method, or force fork.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/sam/Gentoo/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/sam/Gentoo/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/sam/Gentoo/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sam/Gentoo/var/tmp/portage/dev-python/snakeoil-9999/work/snakeoil-9999/setup.py", line 23, in <module>
    setup(**dict(
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/sam/Gentoo/var/tmp/portage/dev-python/snakeoil-9999/work/snakeoil-9999/src/snakeoil/dist/distutils_extensions.py", line 629, in run
    cythonize(self.extensions, nthreads=cpu_count())
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1078, in cythonize
    pool = multiprocessing.Pool(
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
generating version info: /Users/sam/Gentoo/var/tmp/portage/dev-python/snakeoil-9999/work/snakeoil-9999-python3_8/lib/snakeoil/_verinfo.py
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
running config
generating version info: /Users/sam/Gentoo/var/tmp/portage/dev-python/snakeoil-9999/work/snakeoil-9999-python3_8/lib/snakeoil/_verinfo.py
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
running config
```

**Comment by thesamesam** [comment]
I've worked around this for now by applying the workaround within Cython. Fundamentally, it's a Cython bug, so I guess we could close this.
