### ISSUE TITLE
Snakeoil installation fail with "this module is only meant to be imported in setup.py scripts"

### ISSUE THREAD

**Issue by ikus060** [pkgcore/snakeoil#69]
Since July 14, Installing snakeoil is failing with the following error.

```
$ python3 --version
Python 3.10.4
$ pip --version
pip 22.0.2
$ pip install snakeoil
Collecting snakeoil
  Downloading snakeoil-0.9.10.tar.gz (264 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.4/264.4 KB 4.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-1fi7_zy0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-1fi7_zy0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-1fi7_zy0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
        File "/tmp/pip-install-davrjez1/snakeoil_e24e44b56d7249d494682ea944eff3b8/src/snakeoil/dist/distutils_extensions.py", line 54, in <module>
          raise ImportError('this module is only meant to be imported in setup.py scripts')
      ImportError: this module is only meant to be imported in setup.py scripts
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by laumann** [comment]
@ikus060 Thanks for reporting, the current suspicion is that this is caused by newer versions of setuptools - can I ask what version of setuptools you're using?

**Comment by ikus060** [comment]
I've found the failing pipeline.
https://gitlab.com/ikus-soft/minarca/-/jobs/2723737611

Seams to be running version `52.0.0-4`

**Comment by laumann** [comment]
Thanks! Funny, that's older than what I thought it'd be - in the meantime @arthurzam has stated in other channels that it should indeed be setuptools that causing this problem (it's picking up the distutils_extensions.py when wasn't beforehand).
